require('core.editor')
require('core.keybinds')
require('core.autocommands')
require('core.lsp')

require('colorscheme.cyberdream')
require('plugins.treesitter')
require('plugins.pick')
require('plugins.oil')
require('plugins.autoclose')
